### ISSUE TITLE
How did you unpack `scenario.bin`?

### ISSUE THREAD

**Issue by quiple** [Nodamiki/nodamiki.github.io#1]
I could check the letter `MYZIP` at the beginning of the file, but I don't know how to handle it.

Could you tell me any related data or information?

**Comment by quiple** [comment]
Never mind, I wrote a script and solved it.

**Comment by DefiantCatgirl** [comment]
Sorry for not responding, I haven't been checking this repository for ages. Glad that you solved it! I don't really remember what I did anyway, shame on me for not uploading the scripts back then, but, if despite all odds I recall correctly, it was just a file with a header, file sizes, and then the file data just stitched together.

The quality of these scripts was outright atrocious, but if you may still have any use of them, I think they're here: https://mega.nz/file/SxRQiLbY#10wrQmRuW5Nw1TaACCQzrqo_9k6nM2bLwyGyNQXtEsg
